app:
  image: ibmcom/swift-ubuntu:4.0.3
  ports:
    - "8080:8080"
  volumes:
    - .:/server
  command: bash -c "cd /server && swift package --build-path .build-ubuntu clean && swift build --build-path .build-ubuntu && swift test --build-path .build-ubuntu"
